# Generated by Django 4.1.7 on 2023-02-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchasesCount',
            field=models.IntegerField(),
        ),
    ]
